### ISSUE TITLE
how to train data in batch?

### ISSUE THREAD

**Issue by xiaoaoran** [bknyaz/bmvc_2019#1]
Since the superpixel number generated by SLIC is not fixed, which means the dimension of input with multiple images in a batch are not the same. How to read data in dataloader?

**Comment by bknyaz** [comment]
Hi, you can create a custom collate function that you pass to PyTorch DataLoader. See the example in my another repos https://github.com/bknyaz/graph_nn/blob/master/graph_unet.py#L706 
and here https://github.com/bknyaz/graph_attention_pool/blob/master/graphdata.py#L78.
The idea is to: 
1. compute the maximum number of nodes (superpixels) in the current batch, 
2. zero pad node features and adjacency matrices to make all data of the same shape.

**Comment by xiaoaoran** [comment]
Appreciate!
